- name: install rabbitmq component
  hosts: rabbitmq
  become: 'yes'
  tasks:
    - name: Install repo RPMs
  ansible.builtin.yum:
    name: '{{item}}'
    state: installed
  loop:
    - >-
      curl -s
      https://packagecloud.io/install/repositories/rabbitmq/erlang/script.rpm.sh
      | bash
    - >-
      curl -s
      https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.rpm.sh
      | bash

    - name: Install RabbitMQ
      ansible.builtin.yum:
        name: rabbitmq-server
        state: installed

    - name: Start and enable rabbitmq-server service
      ansible.builtin.service:
        name: rabbitmq-server
        state: started
        enabled: 'yes'

    - name: create rabbitmq roboshop user password
      ansible.builtin.command: rabbitmqctl add_user roboshop roboshop123
    
    - name: Setup Permissions
      ansible.builtin.command: rabbitmqctl set_permissions -p / roboshop ".*" ".*" ".*"
