- name: install redis component
  hosts: redis
  become: 'yes'
  tasks:
    - name: Install Redis repo RPM
      ansible.builtin.yum:
        name: https://rpms.remirepo.net/enterprise/remi-release-8.rpm
        state: installed

    - name: Enable Redis 6.2 from package streams
      ansible.builtin.command: yum module enable redis:remi-6.2 -y

    - name: Install Redis
      ansible.builtin.yum:
        name: redis
        state: installed

    - name: remote connections to redis
      ansible.builtin.replace: null
      path: /etc/redis.conf
      regexp: '127.0.0.1'
      replace: '0.0.0.0'

    - name: Start and Enable redis service
      ansible.builtin.service:
        name: redis
        state: started
        enabled: 'yes'
